### ISSUE TITLE
Warping arbitrary x-y coordinates

### ISSUE THREAD

**Issue by horsto** [zpincus/celltool#4]
Hi @zpincus, I discovered your unwarping code (`warp_images`) through this [forum post ](https://forum.image.sc/t/equivalent-for-matlabs-piecewiselineartransformation2d/51035/4) by Stéfan van der Walt today. It saved me days of struggle! 

I had a follow-up question (just below that post) which I thought I'd just bring up with you directly here too. Having defined a transform through your function I now want to transform an array of x-y coordinates (nx2) from the original space into the warped space. How do I do that?

**Comment by zpincus** [comment]
The `_make_warp(from_points, to_points, x_vals, y_vals)` function will do what you want. `from_points` and `to_points` are as in the main function, and `x_vals` and `y_vals` are sets of x- and y-coordinates of any shape. So if you have a `coords` array of shape `(n, 2)`, then:
```python
x_out, y_out = _make_warp(from_points, to_points, coords[:,0], coords[:,1])
new_coords = numpy.transpose([x_out, y_out])
```
and `new_coords.shape` will be `(n,2)`

**Comment by horsto** [comment]
Great, thanks a lot!

**Comment by decorouz** [comment]
Hi @horsto , 
I have been working on turning @zpincus  code into a transform for scikit-image under the mentorship of @lagru. I would appreciate your review on progress made so far via this PR [7040](https://github.com/scikit-image/scikit-image/pull/7040)
